### ISSUE TITLE
Inconsistent data (IMG0003298.jpg)

### ISSUE THREAD

**Issue by Lucashsmello** [XLR8-07/FracAtlas#1]
Hi!
First of all, many thanks for this public dataset!

In dataset.csv, the row of IMG0003298.jpg has a value of 0 to column 'fractured'. However, this image belongs to the Fractured folder and has a bounding box associated with it.

**Comment by Abedeen25** [comment]
The inconsistency has been addressed in the public dataset and thank you for pointing out the issue.
