### ISSUE TITLE
mAP is not as expected!

### ISSUE THREAD

**Issue by Rushi117108** [XLR8-07/FracAtlas#2]
Hi,

Thank you for providing explanation for running this code.
I have run same as you on same dataset, but not getting mAP as you are getting. Have you used any augmentation techniques if so can you provides some details? 

Thank you

**Comment by XLR8-07** [comment]
Hello @Rushi117108 ,

Thanks for reaching out. We have not used any augmentation techniques rather than YOLOv8's default augmentations. 
However, the weights are randomized and each train iterations may produce different results every time in different configurations.

Thanks
